name: Buf Lint

on:
  push:
    paths:
      - 'backend/**/*.proto'
      - 'common/**/*.proto'
      - 'registry/**/*.proto'
  pull_request:
    paths:
      - 'backend/**/*.proto'
      - 'common/**/*.proto'
      - 'registry/**/*.proto'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: .
